server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: grocery-service
          uri: lb://grocery-service
          predicates:
            - Path=/api/grocery/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path= /auth/**
          filters:
            - AuthenticationFilter

